# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94851137ff6696ed3a34683a96828ab2ef8ce868dd67112dc7c442962bdf97aef9ab29a805b5094bd1e826d955091b58eec79bc27ac85a4117aee0a5ca84a770

test:
  secret_key_base: TODO run rails secret and paste here

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["secret_key_base"] %>

production:
  secret_key_base: <%= ENV["secret_key_base"] %>
